# Generated by Django 5.1.6 on 2025-04-13 09:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreaction',
            name='reaction',
            field=models.CharField(default='like', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='reaction',
            field=models.JSONField(default=api.models.default_reaction),
        ),
    ]
