# Generated by Django 5.1.6 on 2025-02-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
