# Generated by Django 5.1.6 on 2025-03-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='album_covers/'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.FileField(upload_to='album_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to='cover_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.FileField(upload_to='job_images/'),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to='cover_pics/'),
        ),
        migrations.AlterField(
            model_name='pendingsignup',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
