# Generated by Django 5.1.6 on 2025-02-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
