# Generated by Django 5.1.6 on 2025-04-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_events_image_eventimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='views',
        ),
    ]
