# Generated by Django 5.1.6 on 2025-03-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_events_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
