# Generated by Django 5.1.6 on 2025-04-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_admin_note_customuser_approved_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='premium_membership',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='premium_number',
        ),
    ]
