# Generated by Django 5.1.6 on 2025-02-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
