# Generated by Django 5.1.6 on 2025-03-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_jobs_company_name_alter_jobs_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='uploaded_by',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='Student', max_length=10),
        ),
    ]
