# Generated by Django 5.1.6 on 2025-04-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pendingsignup_admin_note_pendingsignup_approved_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='name',
        ),
    ]
