# Generated by Django 5.1.6 on 2025-04-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_customuser_name_remove_pendingsignup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
