# Generated by Django 5.1.6 on 2025-02-24 10:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_album_albumimage_jobimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, default=api.models.get_default_social_links),
        ),
    ]
