# Generated by Django 5.1.6 on 2025-02-24 14:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='views',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='reaction',
            field=models.JSONField(blank=True, default=api.models.get_default_reaction),
        ),
    ]
