# Generated by Django 5.1.6 on 2025-04-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_name_pendingsignup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_phone_no',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='mobile_phone_no',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='profile_updated_on',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='registered_on',
        ),
    ]
