# Generated by Django 5.1.6 on 2025-04-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_customuser_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='home_phone_no',
        ),
        migrations.RemoveField(
            model_name='pendingsignup',
            name='institution_name',
        ),
    ]
