# Generated by Django 5.1.6 on 2025-02-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_jobs_job_type_remove_jobs_salary_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
