# Generated by Django 5.1.6 on 2025-04-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pendingsignup_work_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingsignup',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
