# Generated by Django 5.1.6 on 2025-03-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_jobreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='uploaded_by',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
