# Generated by Django 5.1.6 on 2025-04-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_name_pendingsignup_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
