# Generated by Django 5.1.6 on 2025-04-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_newsroom_newsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsroom',
            name='views',
        ),
    ]
