# Generated by Django 5.2.1 on 2025-07-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_pendingsignup_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingsignup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
