# Generated by Django 5.2.1 on 2025-07-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_pendingsignup_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='uploaded_by',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Admin', 'Admin'), ('Alumni', 'Alumni')], default='Student', max_length=10),
        ),
    ]
