# Generated by Django 5.1.6 on 2025-03-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='room',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
